apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/tetrate/workspaces/bookinfo-ws
spec:
  allow:
    - role: rbac/creator
      subjects:
        # Change the name of the team to the desired one
        - team: organizations/tetrate/teams/Platform
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  fqn: organizations/tetrate/tenants/tetrate/workspaces/bookinfo-ws/trafficgroups/bookinfo-traffic
spec:
  allow:
    - role: rbac/writer
      subjects:
        # Change the name of the user to the desired one
        - user: organizations/tetrate/users/zack
