apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cacerts
  namespace: istio-system
spec:
  secretName: cacerts
  duration: 720h # Duration of the certificate validity period (30 days)
  renewBefore: 360h # Time before the certificate expires when it should be renewed (15 days)
  commonName: istiod.istio-system.svc
  isCA: true
  usages:
  - digital signature
  - key encipherment
  - cert sign
  dnsNames:
  - istiod.istio-system.svc
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
    group: cert-manager.io
