```mermaid
flowchart TD
    A["Ingress"] -- used as input --> B["ingress2gateway"]
    B -- generates --> C["Gateway"] & D["HTTPRoute"]
    E["GatewayClass - manually created"] -- referenced by --> C
    F["Envoy Gateway</br>Gateway Class Controller"] -- implements --> E
```
