apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: httpbin-gateway # Need not be the same as spec.labels.app
  organization: tetrate
  tenant: tetrate
  group: httpbin-gateway
  workspace: httpbin
spec:
  workloadSelector:
    namespace: httpbin
    labels:
      app: httpbin-ingress-gateway # name of Ingress Gateway created for httpbin
  http:
    - name: httpbin
      hostname: 'httpbin.tetrate.com'
      port: 80
      routing:
        rules:
          - route:
              host: 'httpbin/httpbin.httpbin.svc.cluster.local'
              port: 8000
      rateLimiting:
        externalService:
          domain: 'httpbin-ratelimit'
          rateLimitServerUri: 'grpc://ratelimit.ext-ratelimit.svc.cluster.local:8081'
          rules:
            - dimensions:
                - requestHeaders:
                    headerName: ':path'
                    descriptorKey: request-path
