apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ext-ratelimit
data:
  config.yaml: |
    domain: httpbin-ratelimit
    descriptors:
      - key: "request-path"
        rate_limit:
          unit: minute
          requests_per_unit: 4
