apiVersion: traffic.tsb.tetrate.io/v2
kind: ServiceRoute
metadata:
  name: helloworld-client-lb
  group: helloworld-trf
  workspace: helloworld-ws
  tenant: tetrate
  organization: tetrate
spec:
  service: helloworld/helloworld
  subsets:
    - name: v1
      labels:
        version: v1
  stickySession:
    useSourceIp: true
