apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: httpbin-gateway
  group: httpbin-gw
  workspace: httpbin-ws
  tenant: tetrate
  organization: tetrate
spec:
  workloadSelector:
    namespace: httpbin
    labels:
      app: tsb-httpbin-gateway
  http:
    - name: httpbin
      port: 443
      hostname: httpbin.tetrate.com
      tls:
        mode: SIMPLE
        secretName: httpbin-cert
      routing:
        rules:
          - route:
              host: httpbin/httpbin
