apiVersion: security.tsb.tetrate.io/v2
kind: SecuritySetting
metadata:
  organization: tetrate
  tenant: tetrate
  workspace: httpbin
  group: httpbin-security
  name: httpbin-security-settings
spec:
  authorization:
    mode: CLUSTER
    http:
      external:
        uri: 'grpc://127.0.0.1:9191'
