apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: tetrate
  name: httpbin-ws
spec:
  namespaceSelector:
    names:
      - 'demo/httpbin'
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate
  workspace: httpbin-ws
  name: httpbin-gw
spec:
  namespaceSelector:
    names:
      - 'demo/httpbin'
  configMode: BRIDGED
